server:
  port: ${PORT:8080}
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/flashbid}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  jwt:
    secret: ${SPRING_JWT_SECRET:${JWT_SECRET:thisisthesecretkeythisisthesecretkeythisisthesecretkey}}

logging:
  level:
    org.springframework: INFO

app:
  timezone: ${APP_TIMEZONE:Asia/Kolkata}

springdoc:
  api-docs:
    path: /api/apidocs
  swagger-ui:
    path: /swagger-ui.html
