server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      password: ${SPRING_DATA_REDIS_PASSWORD}
      ssl: true

  jwt:
    secret: ${SPRING_JWT_SECRET}

logging:
  level:
    root: INFO

app:
  timezone: ${APP_TIMEZONE:Asia/Kolkata}

springdoc:
  api-docs:
    path: /api/apidocs
  swagger-ui:
    path: /swagger-ui.html
