server:
  port: ${PORT:8080}


logging:
  level:
    root: INFO

app:
  timezone: ${APP_TIMEZONE:Asia/Kolkata}


springdoc:
  api-docs:
    path: /api/apidocs
  swagger-ui:
    path: /swagger-ui.html
