spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      username: ${SPRING_DATA_REDIS_USERNAME}
      password: ${SPRING_DATA_REDIS_PASSWORD}
      ssl:
        enabled: ${SPRING_DATA_REDIS_SSL_ENABLED}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: false

jwt:
  secret: ${SPRING_JWT_SECRET}

app:
  redis:
    pubsub-enabled: true